// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatingAPI.DBContext;

#nullable disable

namespace RatingAPI.Migrations
{
    [DbContext(typeof(BillsContext))]
    [Migration("20220827065712_dataInicial")]
    partial class dataInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("RatingAPI.Entities.Bills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CUIT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Precio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CUIT = 12365986L,
                            Descripcion = "Siete KG de mortadela",
                            Nombre = "Coto",
                            Precio = 6000L
                        },
                        new
                        {
                            Id = 2,
                            CUIT = 12345874L,
                            Descripcion = "De Parana a Rosario",
                            Nombre = "Taxis",
                            Precio = 3000L
                        },
                        new
                        {
                            Id = 3,
                            CUIT = 86865474L,
                            Descripcion = "Devengamiento por prestacion de servicios",
                            Nombre = "Servicio Internet",
                            Precio = 5000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
